In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('aug_train.csv')

# how big is the data?

In [17]:
df.shape

(19158, 14)

# how does the data look like?

In [18]:
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [19]:
# to get random data
df .sample(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
4661,14535,city_114,0.926,Male,Has relevent experience,no_enrollment,Masters,STEM,7,100-500,Pvt Ltd,1,43,0.0
18142,2669,city_162,0.767,NaN,No relevent experience,NaN,NaN,NaN,<1,NaN,Pvt Ltd,never,9,0.0
5949,5581,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,500-999,Pvt Ltd,>4,56,0.0
2113,22927,city_61,0.913,Male,Has relevent experience,no_enrollment,Graduate,STEM,15,<10,Pvt Ltd,3,9,1.0
1053,25810,city_116,0.743,Female,Has relevent experience,no_enrollment,Graduate,STEM,16,NaN,NaN,2,31,0.0

# what is the data type of cols?

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 3.4 MB

# are there any missing values?

In [21]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

# how does the data look mathematically

In [22]:
df.describe()

        enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

# are there duplicate values?

In [23]:
df.duplicated().sum()

np.int64(0)

# how is the correlation between cols?

In [25]:
df.corr(numeric_only=True)

,enrollee_id,city_development_index,training_hours,target
enrollee_id,1.000000,-0.040455,0.000998,0.049475
city_development_index,-0.040455,1.000000,0.001920,-0.341665
training_hours,0.000998,0.001920,1.000000,-0.021577
target,0.049475,-0.341665,-0.021577,1.000000

In [27]:
df.corr(numeric_only=True)['enrollee_id']

enrollee_id               1.000000
city_development_index   -0.040455
training_hours            0.000998
target                    0.049475
Name: enrollee_id, dtype: float64