In [6]:
import pandas as pd

# working with json

In [ ]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
pd.read_json('URL')

# working withSQL

In [ ]:
%pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 2.5 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/11.9 MB 2.3 MB/s eta 0:00:05
     ------ --------------------------------- 1.8/11.9 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.1 MB/s eta 0:00:05
     -------- ------------------------------- 2.6/11.9 MB 2.2 MB/s eta 0:00:05
     ---------- ----------------------------- 3.1/11.9 MB 2.2 MB/s eta 0:00:04
     ----------- ---------------------------- 3.4/11.9 MB 2.1 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.9 MB 2.1 MB/s eta 0:00:04
     --------------- ------------------------ 4.5/11.9 MB 2.1 MB/s eta 0:00:04
     ---------------- ----------------------- 5.0/11.9 MB 2.2 MB/s eta 0:00:04
     ------------------ --------------------- 5.5/11.9 MB 2.2 MB/s eta 0:00:03
     -------------------- ------------------- 6.0/11.9 MB 2.2 MB/s eta 0:00:03
     ----------------------- ---------------- 6.8/11.9 MB 2.3 MB/s eta 0:00:03
     ------------------------ --------------- 7.3/11.9 MB 2.3 MB/s eta 0:00:02
     ------------------------- -------------- 7.6/11.9 MB 2.3 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 2.3 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 2.3 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.2 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.2 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 2.2 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.0 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.0 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.9 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 1.9 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 1.8 MB/s eta 0:00:01
     ---------------------------------- ----- 10.2/11.9 MB 1.8 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 1.8 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 1.8 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 1.8 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 1.8 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.6 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 1.5 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.4 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 1.4 MB/s eta 0:00:01
     ---------------------------------------  11.8/11.9 MB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.3 MB/s  0:00:08
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=980195dfadec7c2462480ecd4f65beeac40bc92bb440ddc4d8ab619b5621f404
  Stored in directory: c:\users\f15ga\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\f15ga\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [ ]:
import mysql.connector

In [8]:
conn = mysql.connector.Connect(host='localhost',user='root',password='',database='world')

In [10]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND' ",conn)

C:\Users\f15ga\AppData\Local\Temp\ipykernel_28764\2182673884.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND' ",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]